### ISSUE TITLE
Clear the block expression if the whole is dropped to the trash bin

### ISSUE THREAD

**Issue by pintergreg** [Nekomajin42/spreadsheet-blocks#2]
Currently one has to drag the inner expression from the starting block to delete it. Which is annoying if one wants to clear the whole thingy. Make it possible to clear the block expression if the whole is dropped to the trash bin.

**Comment by Nekomajin42** [comment]
Only the main block is set to be undeletable. It is a safety measure.

**Comment by pintergreg** [comment]
Actually you could remove all the blocks but the main one of the whole one ir draggesd to the bin.

**Comment by Nekomajin42** [comment]
You can remove every block, except the main block from the menu in the top right corner.
